services:
  - type: web
    name: directus-backend
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: "npm install && npx directus bootstrap"
    startCommand: "npx directus start"
    healthCheckPath: /server/health
    envVars:
      - key: PORT
        value: 8055
      - key: PUBLIC_URL
        sync: false
      - key: ADMIN_EMAIL
        value: mihailmamedov666@gmail.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: KEY
        generateValue: true
      - key: SECRET
        generateValue: true

      - key: DB_CLIENT
        value: pg

      - key: DB_HOST
        fromDatabase:
          name: directus-database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: directus-database
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: directus-database
          property: database
      - key: DB_USER
        fromDatabase:
          name: directus-database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: directus-database
          property: password

      - key: CACHE_ENABLED
        value: "true"
      - key: CACHE_STORE
        value: redis
      - key: REDIS
        fromService:
          type: redis
          name: directus-cache
          property: connectionString

  - type: redis
    name: directus-cache
    plan: free
    region: frankfurt
    ipAllowList: []

databases:
  - name: directus-database
    plan: free
    region: frankfurt
    postgresMajorVersion: "15"
    ipAllowList: []

    
