services:
  - type: web
    name: directus-backend
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "npx directus start"
    healthCheckPath: /server/health
    envVars:
      - key: PORT
        value: "8055"
      - key: PUBLIC_URL
        value: "" # можно будет поменять вручную после деплоя
      - key: DB_CLIENT
        value: pg
      - key: DATABASE_URL
        value: postgresql://kraken_db_6fkk_user:Rq1hCOII1v0kHd1Q5BmxFfTBs2BH8QDb@dpg-d1r35vre5dus73e7b47g-a/kraken_db_6fkk
      - key: CACHE_ENABLED
        value: "true"
      - key: CACHE_STORE
        value: redis
      - key: CACHE_REDIS
        fromService:
          type: redis
          name: directus-cache
          property: connectionString
      - key: ADMIN_EMAIL
        value: mihailmamedov666@gmail.com
      - key: ADMIN_PASSWORD
        value: VVqaz123!
      - key: KEY
        generateValue: true
      - key: SECRET
        generateValue: true

  - type: redis
    name: directus-cache
    plan: free
    ipAllowList: []
