services:
  - type: web
    name: directus-backend
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: "npm install && npx directus bootstrap"
    startCommand: "npx directus start"
    healthCheckPath: /server/health
    envVars:
      - key: PORT
        value: "8055"
      - key: PUBLIC_URL
        value: "" # после создания сервиса зайдёшь и подставишь сюда адрес вручную
      - key: DB_CLIENT
        value: pg
      - key: DATABASE_URL
        fromDatabase:
          name: directus-database
          property: connectionString
      - key: CACHE_ENABLED
        value: "true"
      - key: CACHE_STORE
        value: redis
      - key: CACHE_REDIS
        fromService:
          type: redis
          name: directus-cache
          property: connectionString
      - key: ADMIN_EMAIL
        value: mihailmamedov666@gmail.com
      - key: ADMIN_PASSWORD
        value: VVqaz123!
      - key: KEY
        generateValue: true
      - key: SECRET
        generateValue: true

  - type: redis
    name: directus-cache
    plan: free
    ipAllowList: []

databases:
  - name: directus-database
    plan: free
    postgresMajorVersion: "15"
    databaseName: directus
    user: directus
    ipAllowList:
      - source: 0.0.0.0/0
        description: public access
