services:
  # 1. Веб-сервис для Directus
  - type: web
    name: directus-backend
    env: node
    plan: free
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "npx directus start"
    healthCheckPath: /server/health
    envVars:
      - key: PORT
        value: 8055
      - key: PUBLIC_URL
        fromService:
          type: web
          name: directus-backend
          property: url
      - key: DB_CLIENT
        value: pg
      - fromDatabase:
          name: directus-database
          property: connectionString
      - key: CACHE_ENABLED
        value: "true"
      - key: CACHE_STORE
        value: redis
      - key: CACHE_REDIS
        fromService:
          type: redis
          name: directus-cache
          property: connectionString
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: KEY
        generateValue: true
      - key: SECRET
        generateValue: true

  # 2. База данных PostgreSQL как сервис
  - type: pserv
    name: directus-database
    plan: free
    postgres:
      databaseName: directus
      user: directus

  # 3. Кэш Redis как сервис
  - type: redis
    name: directus-cache
    plan: free
    ipAllowList: [] # Разрешаем доступ отовсюду
