services:
  # 1. Веб-сервис для Directus
  - type: web
    name: kraken-backend  # Можете назвать как угодно
    env: docker
    plan: free
    region: frankfurt
    healthCheckPath: /server/health
    dockerCommand: "node /directus/cli.js start"
    envVars:
      - key: PORT
        value: 8055
      - key: PUBLIC_URL
        fromService:
          type: web
          name: kraken-backend # Важно: имя должно совпадать с name этого сервиса
          property: url
      - key: DB_CLIENT
        value: pg
      - fromDatabase:
          name: kraken-db
          property: connectionString
      - key: CACHE_ENABLED
        value: "true"
      - key: CACHE_STORE
        value: redis
      - key: CACHE_REDIS
        fromService:
          type: redis
          name: kraken-cache
          property: connectionString
      - key: ADMIN_EMAIL
        sync: false # Чтобы не хранить на GitHub
      - key: ADMIN_PASSWORD
        sync: false # Чтобы не хранить на GitHub
      - key: KEY
        generateValue: true
      - key: SECRET
        generateValue: true

# 2. База данных PostgreSQL
databases:
  - name: kraken-db
    plan: free

# 3. Кэш Redis
redis:
  - name: kraken-cache
    plan: free
    ipAllowList: [] # Разрешаем доступ отовсюду
