services:
  - type: web
    name: directus-backend
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: "npm install && npx directus bootstrap"
    startCommand: "npx directus start"
    healthCheckPath: /server/health
    envVars:
      - key: PORT
        value: 8055
      - key: PUBLIC_URL
        sync: false
      - key: DB_CLIENT
        value: pg
      - key: DATABASE_URL
        fromDatabase:
          name: directus-database
          property: connectionString
      - key: CACHE_ENABLED
        value: "true"
      - key: CACHE_STORE
        value: redis
      - key: CACHE_REDIS
        fromService:
          type: redis
          name: directus-cache
          property: connectionString
      - key: ADMIN_EMAIL
        value: mihailmamedov666@gmail.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: KEY
        generateValue: true
      - key: SECRET
        generateValue: true
      - key: STORAGE_LOCATIONS
        value: local
      - key: STORAGE_LOCAL_DRIVER
        value: local
      - key: STORAGE_LOCAL_ROOT
        value: /data/uploads

    disks:
      - name: directus-uploads
        mountPath: /data
        sizeGB: 1

  - type: redis
    name: directus-cache
    plan: free
    region: frankfurt

databases:
  - name: directus-database
    plan: free
    region: frankfurt
    postgresMajorVersion: "15"

    